---
- name: 도커 과정 관리 플레이북
  hosts: dockers
  vars_files: 
    - files/extension.list
  tasks:
  - name:  SElinux 기능 설정 -permissive
    include_tasks: tasks/selinux.yml

  - name: 방화벽 내리기
    include_tasks: tasks/firewall.yaml

  - name: 확장 기능 설치 및 설정
    include_tasks: tasks/extension.yaml

  - name: PS1 변수 설정 및 zsh 설치
    include_tasks: tasks/ps1.yaml  
    
